import MainFooter from '../components/footers/MainFooter';
import MainHeader from '../components/headers/MainHeader';
import { WrapThemeStore } from '../state/ThemeStore';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={'h-full'}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body className="font-inter h-full flex flex-col min-h-screen">
        <WrapThemeStore>
          <MainHeader />
          {children}
          <MainFooter />
        </WrapThemeStore>
      </body>
    </html>
  );
}
